using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sbroenne.PowerPointMcp.Generators.Cli;

/// <summary>
/// Generates CLI command classes and registration.
/// Discovers [ServiceCategory] interfaces from referenced assemblies (Core)
/// to eliminate hard-coded category lists.
/// </summary>
[Generator]
public class CliSettingsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Scan the compilation (including referenced assemblies) for [ServiceCategory] interfaces
        context.RegisterSourceOutput(context.CompilationProvider,
            static (spc, compilation) =>
            {
                var categories = DiscoverCategories(compilation);
                if (categories.Count == 0)
                    return;

                foreach (var (_, registryName, requiresSession) in categories)
                {
                    var cmdCode = GenerateCommandClass(registryName, requiresSession);
                    spc.AddSource($"CliCommand.{registryName}.g.cs", SourceText.From(cmdCode, Encoding.UTF8));
                }

                var regCode = GenerateRegistration(categories);
                spc.AddSource("CliCommandRegistration.Generated.g.cs", SourceText.From(regCode, Encoding.UTF8));
            });
    }

    /// <summary>
    /// Discovers [ServiceCategory] interfaces from referenced assemblies.
    /// This replaces the hard-coded category list — adding a new [ServiceCategory]
    /// interface to Core automatically generates the corresponding CLI command.
    /// Uses string-based attribute matching for cross-compilation robustness.
    /// </summary>
    private static List<(string CliName, string RegistryName, bool RequiresSession)> DiscoverCategories(Compilation compilation)
    {
        var result = new List<(string CliName, string RegistryName, bool RequiresSession)>();

        // Search referenced assemblies for interfaces with [ServiceCategory]
        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly)
                continue;

            foreach (var type in GetAllTypes(assembly.GlobalNamespace))
            {
                if (type.TypeKind != TypeKind.Interface)
                    continue;

                // Use string-based matching (robust across compilation boundaries)
                var attr = type.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name == "ServiceCategoryAttribute" &&
                    a.AttributeClass?.ContainingNamespace?.ToDisplayString() == "Sbroenne.PowerPointMcp.Core.Attributes");
                if (attr == null || attr.ConstructorArguments.Length < 2)
                    continue;

                var categoryPascal = attr.ConstructorArguments[1].Value?.ToString() ?? "";

                // Get McpTool name for deriving CLI command name
                var mcpToolAttr = type.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name == "McpToolAttribute");
                var mcpToolName = mcpToolAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString()
                    ?? $"{attr.ConstructorArguments[0].Value}";

                // Check for NoSession attribute
                var noSession = type.GetAttributes().Any(a =>
                    a.AttributeClass?.Name == "NoSessionAttribute");

                var cliName = mcpToolName.Replace("_", "");
                result.Add((cliName, categoryPascal, !noSession));
            }
        }

        return result;
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
            yield return type;
        foreach (var child in ns.GetNamespaceMembers())
            foreach (var type in GetAllTypes(child))
                yield return type;
    }

    private static string GenerateCommandClass(string registryName, bool requiresSession)
    {
        // Fully-qualified Core command implementation for this category, e.g.
        // Sbroenne.PowerPointMcp.Core.Notes.NotesCommands. Naming convention verified across all
        // 9 annotated domains: namespace Sbroenne.PowerPointMcp.Core.{CategoryPascal} contains a
        // sealed class {CategoryPascal}Commands : I{CategoryPascal}Commands.
        var coreCommandsType = $"Sbroenne.PowerPointMcp.Core.{registryName}.{registryName}Commands";
        var actionEnumType = $"Sbroenne.PowerPointMcp.Generated.{registryName}Action";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Sbroenne.PowerPointMcp.CLI.Infrastructure;");
        sb.AppendLine("using Sbroenne.PowerPointMcp.Generated;");
        sb.AppendLine();
        sb.AppendLine("namespace Sbroenne.PowerPointMcp.CLI.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {registryName}Command : ServiceCommandBase<ServiceRegistry.{registryName}.CliSettings>");
        sb.AppendLine("{");
        sb.AppendLine($"    protected override string? GetAction(ServiceRegistry.{registryName}.CliSettings settings) => settings.Action;");
        sb.AppendLine($"    protected override IReadOnlyList<string> ValidActions => ServiceRegistry.{registryName}.ValidActions;");
        sb.AppendLine($"    protected override (string command, object? args) Route(ServiceRegistry.{registryName}.CliSettings settings, string action) => ServiceRegistry.{registryName}.RouteFromSettings(action, settings);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Stateless per-invocation execution for {registryName}: opens the target file (if the");
        sb.AppendLine("    /// action needs one already open), dispatches to Core via the generated");
        sb.AppendLine("    /// ServiceRegistry.DispatchToCore, saves, and disposes — all in this single call. No");
        sb.AppendLine("    /// persistent session/daemon is involved (see squad decision to drop the out-of-process");
        sb.AppendLine("    /// Service).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    protected override string Execute(ServiceRegistry.{registryName}.CliSettings settings, string action, object? args)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (!ServiceRegistry.{registryName}.TryParseAction(action, out var actionEnum))");
        sb.AppendLine($"            throw new System.ArgumentException($\"Unknown action '{{action}}'.\");");
        sb.AppendLine();
        sb.AppendLine("        var argsJson = System.Text.Json.JsonSerializer.Serialize(args);");
        sb.AppendLine($"        var commands = new {coreCommandsType}();");
        sb.AppendLine();

        if (registryName == "Presentation")
        {
            // Presentation.Create/Open are self-contained: Core opens/creates its own batch
            // internally (PresentationSession.CreateNew/BeginBatch) and never touches the batch
            // parameter DispatchToCore's signature still requires — so passing null! is safe and
            // avoids requiring a pre-existing open file for what is, by definition, file creation.
            // Presentation.Save (and any future action needing an already-open file) falls through
            // to the generic path below, which opens --file via BeginBatch first.
            sb.AppendLine($"        if (actionEnum == {actionEnumType}.Create || actionEnum == {actionEnumType}.Open)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var selfContainedResult = ServiceRegistry.{registryName}.DispatchToCore(commands, actionEnum, null!, argsJson);");
            sb.AppendLine("            return selfContainedResult ?? \"{\\\"success\\\":true}\";");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        if (string.IsNullOrWhiteSpace(settings.DocumentPath))");
        sb.AppendLine("            throw new System.ArgumentException(\"A --file <path> is required for this action.\");");
        sb.AppendLine();
        sb.AppendLine("        using var batch = Sbroenne.PowerPointMcp.ComInterop.Session.PresentationSession.BeginBatch(settings.DocumentPath);");
        sb.AppendLine($"        var resultJson = ServiceRegistry.{registryName}.DispatchToCore(commands, actionEnum, batch, argsJson);");

        if (registryName != "Presentation")
        {
            // Every other category's methods only mutate the in-memory batch — the caller must
            // explicitly Save(), mirroring the hand-written placeholder Program.cs (e.g.
            // "slide add-blank" calls PresentationCommands().Save(batch) after SlideCommands().AddBlank).
            // Presentation.Save already calls batch.Save() itself inside DispatchToCore, so no
            // second save is needed there.
            sb.AppendLine("        new Sbroenne.PowerPointMcp.Core.Presentation.PresentationCommands().Save(batch);");
        }

        sb.AppendLine("        return resultJson ?? \"{\\\"success\\\":true}\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRegistration(List<(string CliName, string RegistryName, bool RequiresSession)> categories)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Sbroenne.PowerPointMcp.Generated;");
        sb.AppendLine("using Spectre.Console;");
        sb.AppendLine("using Spectre.Console.Cli;");
        sb.AppendLine();
        sb.AppendLine("namespace Sbroenne.PowerPointMcp.CLI.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class CliCommandRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterCommands(IConfigurator config)");
        sb.AppendLine("    {");
        foreach (var (cliName, registryName, _) in categories.OrderBy(c => c.CliName))
            sb.AppendLine($"        config.AddCommand<{registryName}Command>(\"{cliName}\").WithDescription(ServiceRegistry.{registryName}.Description.EscapeMarkup());");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
