using Sbroenne.PowerPointMcp.CLI.Generated;
using Sbroenne.PowerPointMcp.ComInterop.Session;
using Sbroenne.PowerPointMcp.Core.Presentation;
using Sbroenne.PowerPointMcp.Core.Slide;
using Spectre.Console.Cli;

void PrintUsage()
{
    Console.WriteLine("Usage:");
    Console.WriteLine("  powerpointcli create <path-to-new.pptx>");
    Console.WriteLine("  powerpointcli slide add-blank <path-to.pptx>");
    Console.WriteLine("  powerpointcli slide count <path-to.pptx>");
    Console.WriteLine("  powerpointcli slide delete <path-to.pptx> <slideIndex>");
    Console.WriteLine();
    Console.WriteLine("  powerpointcli <category> <action> --file <path-to.pptx> [options]");
    Console.WriteLine("    where <category> is one of: chart, image, layout, notes, presentation,");
    Console.WriteLine("    shape, table, textframe (source-generated from Core; run");
    Console.WriteLine("    'powerpointcli <category> --help' for actions/options).");
    Console.WriteLine();
    Console.WriteLine("The four hand-written commands above are a minimal placeholder proving the");
    Console.WriteLine("ComInterop -> Core -> CLI vertical slice end to end. Every other command is");
    Console.WriteLine("source-generated by PowerPointMcp.Generators.Cli from the same [ServiceCategory]");
    Console.WriteLine("Core interfaces the MCP server uses. Each invocation is fully self-contained —");
    Console.WriteLine("opens the file, runs one action, saves, and closes — there is no persistent");
    Console.WriteLine("session/daemon (PowerPointMcp deliberately has no out-of-process Service).");
}

if (args.Length == 0)
{
    PrintUsage();
    return 1;
}

// The hand-written legacy verbs ("create", "slide add-blank|count|delete") are intercepted here
// exactly as before. Every other first argument (chart, image, layout, notes, presentation,
// shape, table, textframe) falls through to the source-generated Spectre.Console.Cli commands
// registered below — kept as a *separate* command set rather than replacing "slide" (which the
// generated Slide category also covers) to avoid regressing the one thing already proven to work.
if (args[0] is not ("create" or "slide"))
{
    var app = new CommandApp();
    app.Configure(CliCommandRegistration.RegisterCommands);
    return await app.RunAsync(args);
}

var presentationCommands = new PresentationCommands();
var slideCommands = new SlideCommands();

try
{
    switch (args[0])
    {
        case "create" when args.Length >= 2:
        {
            var result = presentationCommands.Create(args[1]);
            if (!result.Success)
            {
                Console.Error.WriteLine($"Error: {result.ErrorMessage}");
                return 1;
            }
            Console.WriteLine($"Created: {result.PresentationPath}");
            return 0;
        }

        case "slide" when args.Length >= 3 && args[1] == "add-blank":
        {
            using var batch = PresentationSession.BeginBatch(args[2]);
            var result = slideCommands.AddBlank(batch);
            if (!result.Success)
            {
                Console.Error.WriteLine($"Error: {result.ErrorMessage}");
                return 1;
            }
            presentationCommands.Save(batch);
            Console.WriteLine($"Added slide {result.SlideIndex}. Total slides: {result.SlideCount}");
            return 0;
        }

        case "slide" when args.Length >= 3 && args[1] == "count":
        {
            using var batch = PresentationSession.BeginBatch(args[2]);
            var result = slideCommands.GetCount(batch);
            if (!result.Success)
            {
                Console.Error.WriteLine($"Error: {result.ErrorMessage}");
                return 1;
            }
            Console.WriteLine($"{result.SlideCount}");
            return 0;
        }

        case "slide" when args.Length >= 4 && args[1] == "delete":
        {
            if (!int.TryParse(args[3], out int slideIndex))
            {
                Console.Error.WriteLine($"Error: '{args[3]}' is not a valid slide index.");
                return 1;
            }

            using var batch = PresentationSession.BeginBatch(args[2]);
            var result = slideCommands.Delete(batch, slideIndex);
            if (!result.Success)
            {
                Console.Error.WriteLine($"Error: {result.ErrorMessage}");
                return 1;
            }
            presentationCommands.Save(batch);
            Console.WriteLine($"Deleted slide {slideIndex}. Total slides: {result.SlideCount}");
            return 0;
        }

        default:
            PrintUsage();
            return 1;
    }
}
catch (Exception ex)
{
    Console.Error.WriteLine($"Error: {ex.Message}");
    return 1;
}
