#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Checks that every public method on a Core Commands class is declared on its interface.

.DESCRIPTION
    PowerPoint's MCP/CLI action enums (ChartAction, SlideAction, ShapeAction, etc.) are
    auto-generated by the source generator directly from each domain's I*Commands interface
    (see src/PowerPointMcp.Generators). This is intentionally different from mcp-server-excel,
    where a hand-written ToolActions.cs enum is cross-checked against Core via
    audit-core-coverage.ps1 / check-mcp-core-implementations.ps1.

    Because PowerPoint's enums are generator-derived FROM the interface, the Excel bug class
    ("enum value has no Core implementation") is structurally impossible here. The equivalent,
    real risk is the OPPOSITE direction: a concrete *Commands.cs class implements a public method
    that was never added to its I*Commands interface - making it invisible to the generator, so it
    can never be called via MCP or CLI. This exact bug was found for IChartCommands.GetLegendVisibility
    (implementation existed, interface declaration did not) prior to this script's creation.

    This script scans every Core domain folder (src/PowerPointMcp.Core/<Domain>/), finds the
    I*Commands interface and its implementing *Commands class(es) (including partial classes
    split across multiple files), and flags any public instance method present on the class but
    absent from the interface.

.EXAMPLE
    .\check-core-interface-completeness.ps1

.NOTES
    New script - NOT a port from mcp-server-excel (architecture differs; see description).
    Run as part of the pre-commit hook.
#>

param(
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"
$rootDir = Split-Path -Parent $PSScriptRoot
$coreDir = Join-Path $rootDir "src\PowerPointMcp.Core"

# Domain folders to skip (not a Commands domain)
$skipDirs = @("Attributes", "Utilities", "bin", "obj")

function Get-InterfaceMethodNames {
    param([string]$FilePath)

    $text = Get-Content $FilePath -Raw

    # Strip /// XML doc comments and // line comments to avoid false matches
    $text = $text -replace '///.*', ''
    $text = $text -replace '(?m)//.*$', ''

    # Match interface method signatures: <ReturnType> <Name>(...); possibly spanning multiple lines.
    # Interface methods have no body - they end in ");" (optionally with attributes before them).
    $pattern = '(?ms)(?<!new\s)\b(?:Task(?:<[^>]+>)?|void|[A-Za-z_][\w\.\[\]<>,\s?]*)\s+(?<name>[A-Za-z_]\w*)\s*\((?:[^()]|\((?:[^()]*)\))*\)\s*;'
    $names = @()
    foreach ($m in [regex]::Matches($text, $pattern)) {
        $names += $m.Groups['name'].Value
    }
    return $names | Sort-Object -Unique
}

function Get-ClassMethodNames {
    param([string[]]$FilePaths, [string]$ClassName)

    $names = @()
    foreach ($path in $FilePaths) {
        $text = Get-Content $path -Raw
        $text = $text -replace '///.*', ''
        $text = $text -replace '(?m)//.*$', ''

        # Match public instance methods with a body: "public [async] <ReturnType> <Name>(...)"
        # followed eventually by "{". Exclude constructors (name == ClassName) and properties
        # (no parentheses immediately after the name is handled naturally by requiring "(").
        $pattern = '(?ms)\bpublic\s+(?:static\s+|virtual\s+|override\s+|async\s+)*(?:Task(?:<[^>]+>)?|void|[A-Za-z_][\w\.\[\]<>,\s?]*)\s+(?<name>[A-Za-z_]\w*)\s*\((?:[^()]|\((?:[^()]*)\))*\)\s*(?:where[^{]+)?\{'
        foreach ($m in [regex]::Matches($text, $pattern)) {
            $name = $m.Groups['name'].Value
            if ($name -eq $ClassName) { continue } # constructor
            $names += $name
        }
    }
    return $names | Sort-Object -Unique
}

$violations = @()
$domainsChecked = 0

Get-ChildItem -Path $coreDir -Directory | ForEach-Object {
    $domainDir = $_.FullName
    $domainName = $_.Name
    if ($skipDirs -contains $domainName) { return }

    $interfaceFile = Get-ChildItem -Path $domainDir -Filter "I*Commands.cs" -File | Select-Object -First 1
    if (-not $interfaceFile) {
        if ($Verbose) { Write-Host "  Skipping $domainName (no I*Commands.cs interface found)" -ForegroundColor Gray }
        return
    }

    $interfaceName = [IO.Path]::GetFileNameWithoutExtension($interfaceFile.Name) # e.g. IChartCommands
    $className = $interfaceName.Substring(1) # ChartCommands

    # Find the implementing class file(s) - the class may be split into partials across
    # multiple files (e.g. ChartCommands.cs, ChartCommands.Layout.cs), all in the same folder.
    $classFiles = Get-ChildItem -Path $domainDir -Filter "$className*.cs" -File |
        Where-Object { $_.Name -ne $interfaceFile.Name } |
        ForEach-Object { $_.FullName }

    if (-not $classFiles -or $classFiles.Count -eq 0) {
        if ($Verbose) { Write-Host "  Skipping $domainName (no implementing class found for $interfaceName)" -ForegroundColor Gray }
        return
    }

    $domainsChecked++

    $interfaceMethods = Get-InterfaceMethodNames -FilePath $interfaceFile.FullName
    $classMethods = Get-ClassMethodNames -FilePaths $classFiles -ClassName $className

    $missingFromInterface = $classMethods | Where-Object { $_ -notin $interfaceMethods }

    foreach ($method in $missingFromInterface) {
        $violations += [PSCustomObject]@{
            Domain    = $domainName
            Interface = $interfaceName
            Class     = $className
            Method    = $method
        }
    }
}

Write-Host "Checked $domainsChecked Core domain(s) for interface/implementation drift" -ForegroundColor Cyan

if ($violations.Count -eq 0) {
    Write-Host "All public Commands methods are declared on their interface" -ForegroundColor Green
    exit 0
}

Write-Host ""
Write-Host "METHODS IMPLEMENTED BUT NOT DECLARED ON INTERFACE: $($violations.Count)" -ForegroundColor Red
Write-Host "These methods are invisible to the MCP/CLI generators and can never be called!" -ForegroundColor Yellow
Write-Host ""

foreach ($v in $violations) {
    Write-Host "  $($v.Domain): $($v.Class).$($v.Method)() is not declared on $($v.Interface)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Fix: add the missing method signature(s) to the interface, or remove the orphaned" -ForegroundColor Red
Write-Host "     implementation if it is genuinely unused." -ForegroundColor Red
exit 1
